title: CJL's Blog
SEOTitle: CJL的博客
header-img: img/base/page_home.jpg
email: cenjinglun@qq.com
description: "CJL的博客"
keyword: "CJL,@CJL, CJL的博客, CJL Blog, 博客, 个人网站, 前端, 设计"
url: "https://cenjinglun.com/"
baseurl: "" 

future: true

# weibo_username: 
# zhihu_username: 
# github_username: cenjinglun
# twitter_username: 
# facebook_username:  
# linkedin_username:  

highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
  ]
anchorjs: true 

plugins: [jekyll-paginate]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


sidebar: true

featured-tags: true
featured-condition-size: 0 

chrome-tab-theme-color: "#000000"
service-worker: false

page-mathjax: true
